version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./laravel/:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network-ferremas

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./laravel/:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network-ferremas

  #MySQL Service
  db:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:3306"
    environment:
      - SERVICE_TAGS=dev
      - MYSQL_DATABASE=ferremas
      - SERVICE_NAME=mysql
      - MYSQL_USER=usuario-bd
      - MYSQL_PASSWORD=mWQoUvbHbNK5Y8bg
      - MYSQL_ROOT_PASSWORD=v834rQQ45uKtYNZE
    volumes:
      - ./docker/dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network-ferremas

#Docker Networks
networks:
  app-network-ferremas:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
